# Generated by Django 5.2.17 on 2026-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_subscribers', models.PositiveIntegerField(default=0)),
                ('max_subscribers', models.PositiveIntegerField(default=1000000)),
                ('min_views', models.PositiveIntegerField(default=0)),
                ('max_days_since_posting', models.PositiveIntegerField(default=30)),
                ('additional_criteria', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
